CREATE TABLE `tb_troubleshoot_case` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `case_no` VARCHAR(64) NOT NULL COMMENT 'case number',
  `uid` VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'business user id, supports numeric or string ids',
  `source` VARCHAR(32) NOT NULL COMMENT 'source platform: lark/feishu/web',
  `chat_id` VARCHAR(128) NULL COMMENT 'chat id',
  `thread_id` VARCHAR(128) NULL COMMENT 'thread id',
  `message_id` VARCHAR(128) NULL COMMENT 'source message id',
  `reporter_user_id` VARCHAR(128) NULL COMMENT 'source platform reporter user id',
  `original_text` TEXT NULL COMMENT 'original user text',
  `ocr_text` TEXT NULL COMMENT 'image recognition text',
  `issue_domain` VARCHAR(64) NULL COMMENT 'issue domain',
  `issue_type` VARCHAR(64) NULL COMMENT 'issue type',
  `case_status` VARCHAR(64) NOT NULL COMMENT 'case business status',
  `priority` VARCHAR(32) NOT NULL DEFAULT 'normal' COMMENT 'case priority',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT 'case timezone',
  `occurred_at` DATETIME NULL COMMENT 'issue occurred time',
  `closed_at` DATETIME NULL COMMENT 'case closed time',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT 'optimistic lock version',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_case_no` (`case_no`),
  KEY `idx_uid_update_time` (`uid`, `update_time`),
  KEY `idx_case_status_update_time` (`case_status`, `update_time`),
  KEY `idx_domain_type` (`issue_domain`, `issue_type`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='troubleshooting case table';

CREATE TABLE `tb_troubleshoot_case_entity` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `case_id` BIGINT NOT NULL COMMENT 'case id',
  `entity_type` VARCHAR(64) NOT NULL COMMENT 'entity type',
  `entity_value` VARCHAR(255) NOT NULL COMMENT 'entity value',
  `source` VARCHAR(32) NOT NULL COMMENT 'entity source',
  `confidence` DECIMAL(5,4) NULL COMMENT 'entity confidence',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  KEY `idx_case_entity` (`case_id`, `entity_type`),
  KEY `idx_entity_value` (`entity_type`, `entity_value`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='case entity table';

CREATE TABLE `tb_troubleshoot_case_message` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `case_id` BIGINT NOT NULL COMMENT 'case id',
  `role` VARCHAR(32) NOT NULL COMMENT 'message role',
  `platform_message_id` VARCHAR(128) NULL COMMENT 'source platform message id',
  `content` TEXT NOT NULL COMMENT 'message content',
  `content_type` VARCHAR(32) NOT NULL DEFAULT 'text' COMMENT 'message content type',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  KEY `idx_case_create_time` (`case_id`, `create_time`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='case message table';

CREATE TABLE `tb_troubleshoot_investigation` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `investigation_no` VARCHAR(64) NOT NULL COMMENT 'investigation number',
  `case_id` BIGINT NOT NULL COMMENT 'case id',
  `agent_id` VARCHAR(128) NOT NULL COMMENT 'agent id',
  `agent_version` VARCHAR(64) NULL COMMENT 'agent version',
  `model_provider` VARCHAR(64) NULL COMMENT 'model provider',
  `model_name` VARCHAR(128) NULL COMMENT 'model name',
  `investigation_status` VARCHAR(64) NOT NULL COMMENT 'investigation business status',
  `initial_hypothesis` TEXT NULL COMMENT 'initial hypothesis',
  `final_summary` TEXT NULL COMMENT 'final summary',
  `confidence` DECIMAL(5,4) NULL COMMENT 'summary confidence',
  `started_at` DATETIME NOT NULL COMMENT 'investigation start time',
  `finished_at` DATETIME NULL COMMENT 'investigation finish time',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_investigation_no` (`investigation_no`),
  KEY `idx_case_id` (`case_id`),
  KEY `idx_investigation_status_update_time` (`investigation_status`, `update_time`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='investigation table';

CREATE TABLE `tb_troubleshoot_ai_decision_log` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `case_id` BIGINT NOT NULL COMMENT 'case id',
  `investigation_id` BIGINT NULL COMMENT 'investigation id',
  `agent_id` VARCHAR(128) NOT NULL COMMENT 'agent id',
  `decision_type` VARCHAR(64) NOT NULL COMMENT 'decision type',
  `reason` TEXT NULL COMMENT 'decision reason',
  `input_snapshot_json` TEXT NULL COMMENT 'redacted input snapshot json',
  `output_snapshot_json` TEXT NULL COMMENT 'redacted output snapshot json',
  `selected_tools_json` TEXT NULL COMMENT 'selected tools json',
  `decision_status` VARCHAR(32) NOT NULL COMMENT 'decision business status',
  `latency_ms` BIGINT NULL COMMENT 'decision latency milliseconds',
  `error_message` TEXT NULL COMMENT 'error message',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  KEY `idx_case_create_time` (`case_id`, `create_time`),
  KEY `idx_investigation_create_time` (`investigation_id`, `create_time`),
  KEY `idx_decision_type_create_time` (`decision_type`, `create_time`),
  KEY `idx_decision_status_create_time` (`decision_status`, `create_time`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ai decision log table';

CREATE TABLE `tb_troubleshoot_tool_call_audit` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `tool_call_id` VARCHAR(64) NOT NULL COMMENT 'tool call id',
  `case_ref` VARCHAR(64) NOT NULL COMMENT 'case reference',
  `investigation_ref` VARCHAR(64) NULL COMMENT 'investigation reference',
  `agent_id` VARCHAR(128) NOT NULL COMMENT 'agent id',
  `caller_user_id` VARCHAR(128) NULL COMMENT 'caller user id',
  `tool_name` VARCHAR(128) NOT NULL COMMENT 'tool name',
  `required_scope` VARCHAR(128) NULL COMMENT 'required scope',
  `arguments_summary` TEXT NULL COMMENT 'redacted arguments summary',
  `policy_decision` VARCHAR(32) NOT NULL COMMENT 'policy decision',
  `deny_reason` VARCHAR(255) NULL COMMENT 'deny reason',
  `query_id` VARCHAR(128) NULL COMMENT 'downstream query id',
  `result_count` INT NULL COMMENT 'result count',
  `latency_ms` BIGINT NULL COMMENT 'latency milliseconds',
  `error_message` TEXT NULL COMMENT 'error message',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_tool_call_id` (`tool_call_id`),
  KEY `idx_case_create_time` (`case_ref`, `create_time`),
  KEY `idx_tool_create_time` (`tool_name`, `create_time`),
  KEY `idx_agent_create_time` (`agent_id`, `create_time`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='tool call audit table';

CREATE TABLE `tb_troubleshoot_root_cause` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `case_id` BIGINT NOT NULL COMMENT 'case id',
  `ai_predicted_reason` TEXT NULL COMMENT 'ai predicted reason',
  `human_confirmed_reason` TEXT NOT NULL COMMENT 'human confirmed reason',
  `root_cause_category` VARCHAR(128) NOT NULL COMMENT 'root cause category',
  `owner_service` VARCHAR(128) NULL COMMENT 'owner service',
  `owner_team` VARCHAR(128) NULL COMMENT 'owner team',
  `is_cache_issue` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'whether cache issue',
  `is_data_sync_issue` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'whether data sync issue',
  `is_external_source_issue` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'whether external source issue',
  `is_frontend_display_issue` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'whether frontend display issue',
  `is_user_misunderstanding` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'whether user misunderstanding',
  `fix_action` TEXT NULL COMMENT 'fix action',
  `prevention_action` TEXT NULL COMMENT 'prevention action',
  `confirmed_by` VARCHAR(128) NULL COMMENT 'confirmed by',
  `confirmed_at` DATETIME NOT NULL COMMENT 'confirmed time',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_case_id` (`case_id`),
  KEY `idx_root_cause_category` (`root_cause_category`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='root cause table';

CREATE TABLE `tb_troubleshoot_knowledge_item` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `title` VARCHAR(255) NOT NULL COMMENT 'knowledge title',
  `issue_domain` VARCHAR(64) NOT NULL COMMENT 'issue domain',
  `issue_type` VARCHAR(64) NULL COMMENT 'issue type',
  `typical_description` TEXT NULL COMMENT 'typical description',
  `typical_ocr_features` TEXT NULL COMMENT 'typical ocr features',
  `required_fields_json` TEXT NULL COMMENT 'required fields json',
  `recommended_steps_json` TEXT NULL COMMENT 'recommended steps json',
  `common_causes_json` TEXT NULL COMMENT 'common causes json',
  `useful_tools_json` TEXT NULL COMMENT 'useful tools json',
  `success_case_ids_json` TEXT NULL COMMENT 'success case ids json',
  `failure_case_ids_json` TEXT NULL COMMENT 'failure case ids json',
  `confidence` DECIMAL(5,4) NULL COMMENT 'knowledge confidence',
  `knowledge_status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT 'knowledge business status',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  KEY `idx_domain_type` (`issue_domain`, `issue_type`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='knowledge item table';

CREATE TABLE `tb_troubleshoot_agent_registry` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `agent_id` VARCHAR(128) NOT NULL COMMENT 'agent id',
  `name` VARCHAR(128) NOT NULL COMMENT 'agent name',
  `client_id` VARCHAR(128) NOT NULL COMMENT 'client id',
  `client_secret_hash` VARCHAR(255) NOT NULL COMMENT 'client secret hash',
  `allowed_scopes_json` TEXT NOT NULL COMMENT 'allowed scopes json',
  `allowed_tools_json` TEXT NOT NULL COMMENT 'allowed tools json',
  `allowed_lark_groups_json` TEXT NULL COMMENT 'allowed lark groups json',
  `agent_status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT 'agent business status',
  `rate_limit_qps` INT NOT NULL DEFAULT 5 COMMENT 'rate limit qps',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_agent_id` (`agent_id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_agent_status` (`agent_status`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='agent registry table';

CREATE TABLE `tb_troubleshoot_tool_registry` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `tool_name` VARCHAR(128) NOT NULL COMMENT 'tool name',
  `description` TEXT NOT NULL COMMENT 'tool description',
  `input_schema_json` TEXT NOT NULL COMMENT 'input schema json',
  `output_schema_json` TEXT NULL COMMENT 'output schema json',
  `required_scope` VARCHAR(128) NOT NULL COMMENT 'required scope',
  `backend_handler` VARCHAR(128) NOT NULL COMMENT 'backend handler',
  `max_time_range_minutes` INT NULL COMMENT 'max time range minutes',
  `max_limit` INT NULL COMMENT 'max result limit',
  `sensitivity_level` VARCHAR(32) NOT NULL DEFAULT 'normal' COMMENT 'sensitivity level',
  `tool_status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT 'tool business status',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_tool_name` (`tool_name`),
  KEY `idx_tool_status` (`tool_status`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='tool registry table';
