CREATE TABLE IF NOT EXISTS `tb_troubleshoot_ai_decision_log` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `case_id` BIGINT NOT NULL COMMENT 'case id',
  `investigation_id` BIGINT NULL COMMENT 'investigation id',
  `agent_id` VARCHAR(128) NOT NULL COMMENT 'agent id',
  `decision_type` VARCHAR(64) NOT NULL COMMENT 'decision type',
  `reason` TEXT NULL COMMENT 'decision reason',
  `input_snapshot_json` TEXT NULL COMMENT 'redacted input snapshot json',
  `output_snapshot_json` TEXT NULL COMMENT 'redacted output snapshot json',
  `selected_tools_json` TEXT NULL COMMENT 'selected tools json',
  `decision_status` VARCHAR(32) NOT NULL COMMENT 'decision business status',
  `latency_ms` BIGINT NULL COMMENT 'decision latency milliseconds',
  `error_message` TEXT NULL COMMENT 'error message',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  KEY `idx_case_create_time` (`case_id`, `create_time`),
  KEY `idx_investigation_create_time` (`investigation_id`, `create_time`),
  KEY `idx_decision_type_create_time` (`decision_type`, `create_time`),
  KEY `idx_decision_status_create_time` (`decision_status`, `create_time`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ai decision log table';
