CREATE TABLE `tb_troubleshoot_business_service` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `service_name` VARCHAR(128) NOT NULL COMMENT 'service name',
  `owner_team` VARCHAR(128) NULL COMMENT 'owner team',
  `environment` VARCHAR(32) NOT NULL DEFAULT 'local' COMMENT 'runtime environment',
  `base_url` VARCHAR(512) NULL COMMENT 'readonly adapter base url',
  `health_check_path` VARCHAR(256) NULL COMMENT 'health check path',
  `auth_type` VARCHAR(32) NOT NULL DEFAULT 'bearer' COMMENT 'adapter auth type',
  `secret_ref` VARCHAR(128) NULL COMMENT 'environment variable or secret ref for adapter token',
  `service_status` VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'service business status',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_service_name` (`service_name`),
  KEY `idx_service_status` (`service_status`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='business readonly service table';

CREATE TABLE `tb_troubleshoot_mcp_server` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `server_name` VARCHAR(128) NOT NULL COMMENT 'mcp server name',
  `service_name` VARCHAR(128) NOT NULL COMMENT 'service name',
  `transport_type` VARCHAR(32) NOT NULL DEFAULT 'stdio' COMMENT 'mcp transport type',
  `endpoint_url` VARCHAR(512) NULL COMMENT 'sse/http endpoint url',
  `command_json` TEXT NULL COMMENT 'stdio command json',
  `args_json` TEXT NULL COMMENT 'stdio args json',
  `env_json` TEXT NULL COMMENT 'safe env key json, no secret value',
  `protocol_version` VARCHAR(64) NULL COMMENT 'mcp protocol version',
  `request_timeout_seconds` INT NOT NULL DEFAULT 5 COMMENT 'request timeout seconds',
  `secret_ref` VARCHAR(128) NULL COMMENT 'environment variable or secret ref for adapter token',
  `server_status` VARCHAR(32) NOT NULL DEFAULT 'pending_discovery' COMMENT 'mcp server business status',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  KEY `idx_service_name` (`service_name`),
  KEY `idx_server_status` (`server_status`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='mcp server registry table';

ALTER TABLE `tb_troubleshoot_tool_registry`
  ADD COLUMN `service_name` VARCHAR(128) NULL COMMENT 'service name' AFTER `description`,
  ADD COLUMN `source_type` VARCHAR(32) NOT NULL DEFAULT 'builtin' COMMENT 'tool source type' AFTER `service_name`,
  ADD COLUMN `readonly_base_url` VARCHAR(512) NULL COMMENT 'readonly adapter base url' AFTER `backend_handler`,
  ADD COLUMN `readonly_path` VARCHAR(256) NULL COMMENT 'readonly endpoint path' AFTER `readonly_base_url`,
  ADD COLUMN `http_method` VARCHAR(16) NOT NULL DEFAULT 'POST' COMMENT 'readonly http method' AFTER `readonly_path`,
  ADD COLUMN `secret_ref` VARCHAR(128) NULL COMMENT 'environment variable or secret ref for adapter token' AFTER `http_method`,
  ADD COLUMN `mcp_server_id` BIGINT NULL COMMENT 'mcp server id' AFTER `secret_ref`,
  ADD COLUMN `mcp_tool_name` VARCHAR(128) NULL COMMENT 'mcp tool name' AFTER `mcp_server_id`,
  ADD COLUMN `param_map_json` TEXT NULL COMMENT 'gateway to backend param map json' AFTER `mcp_tool_name`,
  ADD COLUMN `fixed_params_json` TEXT NULL COMMENT 'fixed params json' AFTER `param_map_json`,
  ADD COLUMN `required_params_json` TEXT NULL COMMENT 'required params json' AFTER `fixed_params_json`,
  ADD COLUMN `optional_params_json` TEXT NULL COMMENT 'optional params json' AFTER `required_params_json`,
  ADD COLUMN `timeout_ms` INT NULL COMMENT 'single call timeout ms' AFTER `optional_params_json`,
  ADD COLUMN `safety_status` VARCHAR(32) NOT NULL DEFAULT 'readonly_candidate' COMMENT 'safety review status' AFTER `timeout_ms`,
  ADD COLUMN `safety_reasons_json` TEXT NULL COMMENT 'safety review reasons json' AFTER `safety_status`,
  ADD COLUMN `approval_status` VARCHAR(32) NOT NULL DEFAULT 'approved' COMMENT 'approval business status' AFTER `safety_reasons_json`,
  ADD COLUMN `validation_status` VARCHAR(32) NOT NULL DEFAULT 'not_run' COMMENT 'validation business status' AFTER `approval_status`,
  ADD COLUMN `created_by` VARCHAR(128) NULL COMMENT 'created by' AFTER `validation_status`,
  ADD COLUMN `published_by` VARCHAR(128) NULL COMMENT 'published by' AFTER `created_by`,
  ADD COLUMN `published_at` DATETIME NULL COMMENT 'published time' AFTER `published_by`,
  ADD KEY `idx_service_source` (`service_name`, `source_type`),
  ADD KEY `idx_safety_approval` (`safety_status`, `approval_status`);

CREATE TABLE `tb_troubleshoot_tool_validation_run` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `tool_id` BIGINT NULL COMMENT 'tool registry id',
  `mcp_server_id` BIGINT NULL COMMENT 'mcp server id',
  `run_type` VARCHAR(64) NOT NULL COMMENT 'validation run type',
  `run_status` VARCHAR(32) NOT NULL COMMENT 'validation run business status',
  `input_snapshot_json` TEXT NULL COMMENT 'input snapshot json',
  `output_snapshot_json` TEXT NULL COMMENT 'output snapshot json',
  `error_message` TEXT NULL COMMENT 'error message',
  `created_by` VARCHAR(128) NULL COMMENT 'created by',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  KEY `idx_tool_id` (`tool_id`),
  KEY `idx_mcp_server_id` (`mcp_server_id`),
  KEY `idx_run_status` (`run_status`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='tool validation run table';
