CREATE TABLE IF NOT EXISTS `tb_troubleshoot_agent_runtime` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `runtime_id` VARCHAR(128) NOT NULL COMMENT 'runtime id',
  `runtime_name` VARCHAR(128) NOT NULL COMMENT 'runtime name',
  `runtime_type` VARCHAR(32) NOT NULL DEFAULT 'local' COMMENT 'runtime type: local/cloud',
  `host_name` VARCHAR(128) NULL COMMENT 'runtime host name',
  `provider_list_json` TEXT NULL COMMENT 'available agent providers json',
  `workspace_root` VARCHAR(512) NULL COMMENT 'local workspace root',
  `runtime_status` VARCHAR(32) NOT NULL DEFAULT 'registered' COMMENT 'runtime business status',
  `last_heartbeat_at` DATETIME NULL COMMENT 'last heartbeat time',
  `registered_at` DATETIME NOT NULL COMMENT 'registered time',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_runtime_id` (`runtime_id`),
  KEY `idx_runtime_status_update_time` (`runtime_status`, `update_time`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='agent runtime table';

CREATE TABLE IF NOT EXISTS `tb_troubleshoot_agent_run` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `run_no` VARCHAR(64) NOT NULL COMMENT 'agent run number',
  `case_id` BIGINT NOT NULL COMMENT 'case id',
  `investigation_id` BIGINT NULL COMMENT 'investigation id',
  `parent_run_id` BIGINT NULL COMMENT 'parent agent run id',
  `runtime_id` VARCHAR(128) NULL COMMENT 'runtime id',
  `agent_name` VARCHAR(128) NOT NULL COMMENT 'agent name',
  `agent_role` VARCHAR(64) NOT NULL COMMENT 'agent role',
  `trigger_type` VARCHAR(64) NOT NULL COMMENT 'trigger type',
  `run_status` VARCHAR(32) NOT NULL COMMENT 'run business status',
  `input_summary` TEXT NULL COMMENT 'bounded input summary',
  `output_summary` TEXT NULL COMMENT 'bounded output summary',
  `model_provider` VARCHAR(64) NULL COMMENT 'model provider',
  `model_name` VARCHAR(128) NULL COMMENT 'model name',
  `started_at` DATETIME NULL COMMENT 'run start time',
  `finished_at` DATETIME NULL COMMENT 'run finish time',
  `latency_ms` BIGINT NULL COMMENT 'run latency milliseconds',
  `error_message` TEXT NULL COMMENT 'error message',
  `payload_json` TEXT NULL COMMENT 'redacted compact payload json',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_run_no` (`run_no`),
  KEY `idx_case_create_time` (`case_id`, `create_time`),
  KEY `idx_case_agent` (`case_id`, `agent_name`, `create_time`),
  KEY `idx_runtime_status` (`runtime_id`, `run_status`),
  KEY `idx_parent_run_id` (`parent_run_id`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='agent run table';

CREATE TABLE IF NOT EXISTS `tb_troubleshoot_agent_run_event` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'primary key',
  `run_id` BIGINT NOT NULL COMMENT 'agent run id',
  `event_seq` INT NOT NULL COMMENT 'sequence within run',
  `event_type` VARCHAR(64) NOT NULL COMMENT 'event type',
  `event_status` VARCHAR(32) NOT NULL DEFAULT 'info' COMMENT 'event business status',
  `title` VARCHAR(255) NOT NULL COMMENT 'event title',
  `summary` TEXT NULL COMMENT 'event summary',
  `payload_json` TEXT NULL COMMENT 'redacted compact payload json',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'row status: 0 deleted, 1 active',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  UNIQUE KEY `uk_run_seq` (`run_id`, `event_seq`),
  KEY `idx_run_create_time` (`run_id`, `create_time`),
  KEY `idx_event_type_create_time` (`event_type`, `create_time`),
  KEY `idx_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='agent run event table';
